# Generated by Django 5.0.2 on 2024-02-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_table',
            name='Department',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
