# Generated by Django 5.0.2 on 2024-02-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide_info',
            name='PanelMember',
            field=models.BooleanField(default=False),
        ),
    ]
