# Generated by Django 4.2.5 on 2023-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadReg_No', models.CharField(max_length=50)),
                ('Staff_Incharge', models.CharField(max_length=100)),
                ('Date_Of_Meeting', models.DateField()),
                ('Work_Completed', models.CharField(max_length=250)),
                ('Work_To_Be_Completed', models.CharField(max_length=250)),
                ('Review', models.BooleanField(default=False)),
            ],
        ),
    ]
