# Generated by Django 4.2.5 on 2023-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstatus', '0002_projectstatus_row_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='Date_Of_Meeting',
            field=models.DateField(auto_now_add=True),
        ),
    ]
