# Generated by Django 4.2.5 on 2023-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstatus', '0003_alter_projectstatus_date_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='Date_Of_Meeting',
            field=models.DateField(),
        ),
    ]
