# Generated by Django 4.2.5 on 2023-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadReg_No', models.CharField(max_length=50, unique=True)),
                ('Lead', models.CharField(max_length=100)),
                ('Staff_Incharge', models.CharField(max_length=100)),
                ('Member1', models.CharField(max_length=100)),
                ('Member2', models.CharField(max_length=100)),
                ('Member3', models.CharField(max_length=100)),
                ('Member4', models.CharField(max_length=100)),
            ],
        ),
    ]
