# Generated by Django 4.2.5 on 2023-10-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamdetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Member4',
        ),
    ]
