# Generated by Django 4.2.5 on 2023-10-03 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=100, unique=True)),
                ('User_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('Batch_No', models.CharField(max_length=10)),
                ('Staff_Incharge', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
            ],
        ),
    ]
