# Generated by Django 4.2.5 on 2023-10-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promgmt', '0002_signin_checking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='Checking',
        ),
    ]
