# Generated by Django 5.0.2 on 2024-02-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panal_review0',
            name='PanalMember_ID',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='panal_review0',
            name='Review0_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panal_review1',
            name='PanalMember_ID',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='panal_review1',
            name='Review1_Status',
            field=models.BooleanField(default=False),
        ),
    ]
