# Generated by Django 5.0.2 on 2024-02-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panal_review0_panalmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panal_review0',
            name='Batch',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review0',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review0',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review0',
            name='Review0_Feedback',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review0',
            name='Review0_Marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='panal_review0',
            name='Year',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='Batch',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='Review1_Feedback',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='Review1_Marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='Year',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='Batch',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='Review2_Feedback',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='Review2_Marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='Year',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='Batch',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='Review3_Feedback',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='Review3_Marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='Year',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
