# Generated by Django 5.0.2 on 2024-02-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_panal_review0_batch_alter_panal_review0_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panal_review2',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='panal_review2',
            name='Review2_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panal_review3',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='panal_review3',
            name='Review3_Status',
            field=models.BooleanField(default=False),
        ),
    ]
