# Generated by Django 5.0.2 on 2024-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_panal_review2_panalmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panal_review0',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='panal_review1',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
