# Generated by Django 5.0.2 on 2024-02-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_panal_review0_panalmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panal_review0',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
