# Generated by Django 5.0.2 on 2024-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_panal_review1_panalmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panal_review1',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
