# Generated by Django 5.0.2 on 2024-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_panal_review1_panalmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panal_review1',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review2',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='panal_review3',
            name='PanalMember_ID',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
