# Generated by Django 4.2.5 on 2023-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_No', models.CharField(max_length=50)),
                ('Project_Guide', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=150)),
                ('lead_RegNo', models.CharField(max_length=50, unique=True)),
                ('Review_0', models.BooleanField(default=False)),
                ('Review_1', models.BooleanField(default=False)),
                ('Review_2', models.BooleanField(default=False)),
                ('Review_3', models.BooleanField(default=False)),
                ('Last_Updated', models.DateField()),
            ],
        ),
    ]
