# Generated by Django 4.2.5 on 2023-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0003_remove_project_review_0_remove_project_review_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Last_Updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
