# Generated by Django 5.0.2 on 2024-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_0',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(default=None, max_length=50)),
                ('Abstract', models.FileField(upload_to='review_0_docs/')),
                ('Base_Paper', models.FileField(upload_to='review_0_docs/')),
                ('PPT', models.FileField(upload_to='review_0_docs/')),
                ('Title_Status', models.BooleanField(default=False)),
                ('Abstract_Status', models.BooleanField(default=False)),
                ('Base_Paper_Status', models.BooleanField(default=False)),
                ('PPt_Status', models.BooleanField(default=False)),
                ('Guide_Status', models.BooleanField(default=False)),
                ('Hod_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
