# Generated by Django 5.0.2 on 2024-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_review_1_architecture_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_3',
            name='Project_Demo',
            field=models.FileField(blank=True, null=True, upload_to='review_3_docs/'),
        ),
    ]
