# Generated by Django 5.0.2 on 2024-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_review_3_project_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_3',
            name='Project_Demo',
            field=models.FileField(blank=True, null=True, upload_to='review_3_docs/video/'),
        ),
    ]
