# Generated by Django 4.2.5 on 2023-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(max_length=50, unique=True)),
                ('Project_Title', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
